# Generated by Django 5.0.6 on 2024-09-10 18:43

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('source', models.CharField(max_length=30, verbose_name='Fuente')),
                ('type', models.CharField(max_length=15, verbose_name='Tipo de metrica')),
                ('base_severity', models.CharField(max_length=50, verbose_name='Severidad')),
                ('exploitability_score', models.PositiveSmallIntegerField(verbose_name='Puntos de exploit')),
                ('impact_score', models.PositiveSmallIntegerField(verbose_name='Puntos de impacto')),
            ],
            options={
                'verbose_name': 'Metrica',
                'verbose_name_plural': 'Metricas',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('cve_id', models.CharField(max_length=50, verbose_name='ID CVE')),
                ('source_identifier', models.CharField(max_length=50, verbose_name='Identificador')),
                ('published', models.CharField(max_length=50, verbose_name='Publicación')),
                ('last_modified', models.CharField(max_length=50, verbose_name='Última modificación')),
                ('vuln_status', models.CharField(max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
            },
        ),
        migrations.CreateModel(
            name='DatoMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('version', models.CharField(max_length=10, verbose_name='Versión')),
                ('vector_string', models.TextField(verbose_name='Vector')),
                ('access_vector', models.CharField(max_length=30, verbose_name='Acceso al vector')),
                ('access_complexity', models.CharField(max_length=15, verbose_name='Complejidad del acceso')),
                ('authentication', models.CharField(max_length=20, verbose_name='Autenticación')),
                ('confidentiality_impact', models.CharField(max_length=30, verbose_name='Confidencialidad del impacto')),
                ('integrity_impact', models.CharField(max_length=30, verbose_name='Integridad del impacto')),
                ('availability_impact', models.CharField(max_length=30, verbose_name='Disponibilidad del impacto')),
                ('base_score', models.SmallIntegerField(verbose_name='Puntuacion base')),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrica_datos_metrica', to='cve.metrica', verbose_name='metrica')),
            ],
            options={
                'verbose_name': 'Dato de la metrica',
                'verbose_name_plural': 'Datos de las metricas',
            },
        ),
        migrations.CreateModel(
            name='SolucionVulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('fecha_solucion', models.DateTimeField(auto_now_add=True)),
                ('vulnerabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucion_vulnerabilidad_vulnerabilidad', to='cve.vulnerabilidad', verbose_name='vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Vulnerabilidad solucionada',
                'verbose_name_plural': 'Vulnerabilidades solucionadas',
            },
        ),
        migrations.AddField(
            model_name='metrica',
            name='vulnerabilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrica_vulnerabilidad', to='cve.vulnerabilidad', verbose_name='vulnerabilidad'),
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('lang', models.CharField(max_length=5, verbose_name='Lenguaje')),
                ('value', models.TextField(verbose_name='Descripción')),
                ('vulnerabilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_vulnerabilidad', to='cve.vulnerabilidad', verbose_name='vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Descripción',
                'verbose_name_plural': 'Descripciones',
            },
        ),
    ]
