# Generated by Django 5.0.6 on 2024-09-11 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datometrica',
            name='metrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_datos_metricas', to='cve.metrica', verbose_name='metrica'),
        ),
        migrations.AlterField(
            model_name='descripcion',
            name='vulnerabilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripciones_vulnerabilidades', to='cve.vulnerabilidad', verbose_name='vulnerabilidad'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='vulnerabilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_vulnerabilidades', to='cve.vulnerabilidad', verbose_name='vulnerabilidad'),
        ),
        migrations.AlterField(
            model_name='solucionvulnerabilidad',
            name='vulnerabilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soluciones_vulnerabilidades_vulnerabilidades', to='cve.vulnerabilidad', verbose_name='vulnerabilidad'),
        ),
    ]
